### PR TITLE
Update rig.lua

### PR DESCRIPTION
**Pull request by landenjw**
Fixes typo that effectively renders the command broken.

### CODE REVIEW

**Comment by ezekieltem** [comment]
It's difficult to actually see the differences because of the different indents used, if possible change the indenting on your end to 4 spaces.

**Comment by landenjw** [comment]
Updated.

**Comment by ezekieltem** [comment]
image
Whats the actual difference?
Are you sure you replaced the entire file with the correct indents?
You can change the type of indents used by studio like this:
image
image
image
image

**Comment by ezekieltem** [comment]
Ended up just copying the raw code from the forked repo, works fine.
Gonna merge, then write over with the formatting used by NA, which will also be the formatting used here.

**Pull request merged**
